### ISSUE TITLE
Adding the mouse option for user to play

### ISSUE THREAD

**Issue by savannahar68** [RITESHMOHAPATRA/TIC-TAC-TOE#11]
Instead of playing the game by inputting the numbers 1-9 for each block we can let user play with mouse,whichever box they'll click will by crossed .I would like to work on this.Also working on undo button

**Comment by savannahar68** [comment]
I would like to work on this issue

**Comment by rabitex** [comment]
why not let this be through keypad only...coz that gives you the feel of a
proper board. And integrate mouse input in the menu instead

On Dec 4, 2017 8:40 AM, "savannahar68" <notifications@github.com> wrote:

Instead of playing the game by inputting the numbers 1-9 for each block we
can let user play with mouse,whichever box they'll click will by crossed .I
would like to work on this.Also working on undo button

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RITESHMOHAPATRA/TIC-TAC-TOE/issues/11>, or mute the
thread

**Comment by rabitex** [comment]
allowing both kinds of input would be absolutely awesome actually

**Comment by savannahar68** [comment]
Yes, it's feasible with the mouse, because not everyone knows the numbering scheme that it starts with right bottom 1 to left top 9.Providing mouse click is kind of flexibility for user I feel

**Comment by rabitex** [comment]
Yes. True

**Comment by rabitex** [comment]
probably because this pr was merged later....the menu feature has been
lost. isnt it

**Comment by RITESHMOHAPATRA** [comment]
MAke another branch with the updated one . I will delete this one. Is that a problem for you???

**Comment by rabitex** [comment]
I am working on clearing bugs in the menu interface. I will send a PR as
soon as I am done with it. That will satisfy all the motives....if its fine.

**Comment by RITESHMOHAPATRA** [comment]
Can I delete  this branch???

**Comment by rabitex** [comment]
yes sure! if you want to.
